### ISSUE TITLE
ReactDOMServer.renderToString results in empty accordion shell.

### ISSUE THREAD

**Issue by jdfm** [springload/react-accessible-accordion#123]
Steps to Reproduce
---

* Follow the create-react-app [instructions](https://github.com/facebook/create-react-app#quick-overview) to create a new project.
* Use the code below in the `src/index.js` file (it's just the example in RAA's `README.md` file with `ReactDOMServer.renderToString` instead of `ReactDOM.render`).
* Run `yarn start` and observe the results in the browser's console.

```javascript
import React from 'react';
import ReactDOMServer from 'react-dom/server';

import {
    Accordion,
    AccordionItem,
    AccordionItemTitle,
    AccordionItemBody,
} from 'react-accessible-accordion';

// Demo styles, see 'Styles' section below for some notes on use.
import 'react-accessible-accordion/dist/fancy-example.css';

const Example = () => (
    <Accordion>
        <AccordionItem>
            <AccordionItemTitle>
                <h3>Simple title</h3>
            </AccordionItemTitle>
            <AccordionItemBody>
                <p>Body content</p>
            </AccordionItemBody>
        </AccordionItem>
        <AccordionItem>
            <AccordionItemTitle>
                <h3>Complex title</h3>
                <div>With a bit of description</div>
            </AccordionItemTitle>
            <AccordionItemBody>
                <p>Body content</p>
            </AccordionItemBody>
        </AccordionItem>
    </Accordion>
);

console.log(ReactDOMServer.renderToString(<Example />));
```

Notes
---

I originally saw this issue happening in the context of a gatsbyjs project, which uses `ReactDOMServer.renderToString` for server side rendering.

For reference, the output that I see in the console is:

```html
<div role="tablist" class="accordion" data-reactroot=""></div>
```

**Comment by jdfm** [comment]
I ran through the render process and found that when AccordionItem renders it checks the `accordionContainer.state.items` array for a `currentItem`, and if it doesn't exist, it returns `null`, effectively resulting in no rendered contents in the final HTML string. 

The first render (which is the case of SSR through `ReactDOMServer.renderToString`) will not have anything in the items array, as AccordionItem only populates that array on `componentDidMount`, which happens after the first render.

**Comment by ryami333** [comment]
Gidday @jdfm, thanks for your issue and my apologies for the delayed response. This was an issue that we were aware of, and it's unfortunately a very difficult one to fix, related to a significant change in one of our dependencies `unstated`. I've made a PR to refactor it away, which you can track [here](https://github.com/springload/react-accessible-accordion/pull/128).

Thanks for your patience :)

**Comment by ryami333** [comment]
@jdfm thanks for your patience - it should be fixed with today's release 🍾 

Would appreciate it you could please try it out for us, and if it looks good then I encourage you close this issue. Thanks again!

**Comment by jdfm** [comment]
I'll try to get to it today or tomorrow, will let you know once I've done so. Thanks for looking into this! Cheers!

**Comment by Pustur** [comment]
@ryami333 I just encountered this problem in my own Gastby project so I was happy to see a new version had been released since I first installed `react-accessible-accordion`.

Unfortunately after upgrading to `2.4.5` the problem still persists. I also tried with a fresh `create-react-app` project as mentioned by @jdfm in the original post and the result is the same.

**Comment by jdfm** [comment]
@ryami333 I just tried it locally, it's still giving me the results I was seeing before unfortunately.

**Comment by ryami333** [comment]
Right you are. I naively assumed that Enzyme's `mount` was equivalent to `renderToString` and used that as my test assertion :/

Unfortunately, this is a far more difficult thing to implement/fix than I first thought. Basically, the way that this project is architected - it _can't_ render AccordionItems on the first render, because they need to register themselves in `context` first.

We might be able to re-architect that now that we've changed the way a couple of things work under the hood, so I'll put this back on our hypothetical Roadmap for more investigation. But please don't hold your breath, it could still be a while away 🙈

**Comment by chendo** [comment]
Is context required for the purposes of hooking into the events? I would be happy if it just rendered the DOM without hooks for SSR so we can have the markup be indexed by search engines.

**Comment by ryami333** [comment]
Yes I understand the use-case and motivation for this feature, it's just that SSR takes a back-seat to a11y compliance, in terms of priority. And yes - as of this moment - we need context to be able to achieve this.

**Comment by Ofekw** [comment]
We're having the same issue - had to roll back to 2.4.2 because of the empty div being rendered.

**Comment by ryami333** [comment]
Approach has been totally overhauled, and SSR has been addressed in `next` branch. Will be published with `3.0.0`.
